#!/bin/bash
# This script sets up the CAR-GALLERY-PRO project from scratch
# optimized for a first-time server or local environment installation.

echo "🚀 Starting CAR-GALLERY-PRO Setup..."
echo "----------------------------------------------------"

# Stop the script on any error
set -e

# --- Step 0: Basic Settings and Functions ---
echo "▶ Checking basic system settings..."
sudo -v # Request sudo password at the beginning

# Error message function
function error_message {
  echo "❌ ERROR: $1"
  echo "Setup stopped."
  exit 1
}

# --- Step 1: PostgreSQL Database and User ---
echo "▶ Setting up PostgreSQL database and user..."
DB_NAME="car_dealer_db"
DB_USER="dealer_user"
DB_PASS="DealerPass123!"

# Check if psql is installed
if ! command -v psql &> /dev/null; then
    error_message "PostgreSQL (psql) is not installed. Please install it first."
fi

# Ensure PostgreSQL service is running
sudo systemctl start postgresql.service || echo "⚠️  Could not start PostgreSQL service via systemctl. Assuming it's already running or managed differently."

echo "--> Creating user and database (if not exist)..."
# Create the user and database using the postgres superuser
sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$DB_USER') THEN CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASS' CREATEDB; END IF; END \$\$;"
sudo -u postgres psql -c "SELECT 'CREATE DATABASE $DB_NAME OWNER $DB_USER' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME')\gexec"

echo "✔ Database '$DB_NAME' and user '$DB_USER' are ready."
echo

# --- Step 2: Setup Environment Variables ---
echo "▶ Configuring .env file..."
if [ -f .env ]; then
    echo "⚠️  .env file already exists. Backing it up to .env.bak"
    cp .env .env.bak
fi

NEXTAUTH_SECRET=$(openssl rand -base64 32)
X_AUTH_TOKEN=$(openssl rand -base64 24)

cat << EOF > .env
# This file was auto-generated by the setup script.

# Database
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}?schema=public"

# NextAuth Configuration
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
NEXTAUTH_URL="http://localhost:3000"

# App Configuration
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_LOCALE="en"

# API Tokens
X_AUTH_TOKEN="${X_AUTH_TOKEN}"

# AWS S3 (Leave blank if not used)
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_REGION=""
AWS_BUCKET_NAME=""
NEXT_PUBLIC_S3_BUCKET_URL=""

# Resend (Email)
RESEND_API_KEY=""

# TinyMCE
NEXT_PUBLIC_TINYMCE_API_KEY=""

# Upstash Redis
UPSTASH_REDIS_REST_URL=""
UPSTASH_REDIS_REST_TOKEN=""

# OpenAI
OPENAI_API_KEY=""
EOF
echo "✔ .env file created successfully with generated secrets."
echo

# --- Step 3: Dependencies ---
echo "▶ Installing dependencies..."
if [ -d node_modules ]; then
    echo "--> Removing existing node_modules..."
    rm -rf node_modules
fi

npm install || error_message "'npm install' failed."
echo "✔ Packages installed successfully."
echo

# --- Step 4: Database Schema and Seeding ---
echo "▶ Syncing database schema..."
# We use migrate dev for first install to ensure everything is initialized
npx prisma migrate dev --name init || error_message "Prisma migration failed."

echo "▶ Seeding database..."
npm run seed || error_message "Database seeding failed."
echo "✔ Database setup and seeding complete."
echo

# --- Step 5: Finish ---
echo "🎉 SETUP SUCCESSFULLY COMPLETED! 🎉"
echo "----------------------------------------------------"
echo "To start the development server:"
echo "npm run dev"
echo ""
echo "To build for production:"
echo "npm run build"
echo "npm start"
echo ""
echo "Admin Login Credentials:"
echo "URL: http://localhost:3000/auth/sign-in"
echo "Email: admin@example.com"
echo "Password: admin123"
echo "----------------------------------------------------"
echo "⚠️  IMPORTANT: Please update AWS, Resend, and Redis keys in your .env file."